# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'
      - run: npm ci
      - uses: jaywcjlove/github-action-package@main
        with:
          data: |
            {
              "version": "${{ github.event.release.tag_name }}"
            }
          unset: publishConfig.registry
      - run: npm run build
      - run: find . ! -name . -printf "%P\n"
        working-directory: dist
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
